services:
  redis:
    image: redis:latest
    container_name: secrets_redis

  secrets:
    image: secrets:latest
    container_name: secrets
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "${SECRETS_PORT:-8080}:8080"

