services:
  redis:
    image: redis:latest
    container_name: secrets_redis

  secrets:
    image: secrets:latest
    container_name: secrets
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "${SECRETS_PORT:-8080}:8080"

  caddy:
    image: caddy:2.9.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${CADDY_CONFIG_PATH:-./caddy}:/etc/caddy
      - caddy-data:/data

volumes:
  caddy-data:
